In [ ]:
#Reading and Writing Data in Text Format
import numpy as np
import pandas as pd
#printing the raw contents of the file
# !type ex1.csv 
df=pd.read_csv("ex1.csv") #csv file to dataFrame
df
print('')
# !type ex2.csv
pd.read_csv('ex2.csv', header=None) #since there is no header row present in the csv file
#We can assign header row.
pd.read_csv('ex2.csv', names=['a','b','c','d','message']) #we can provide header row by passing a list in names
names=['a','b','c','d','message']
# Suppose you wanted the message column to be the index of the returned DataFrame.
# You can either indicate you want the column at index 4 or named "message" using
# the index_col argument
pd.read_csv('ex2.csv', names=names, index_col='message') #or index-col=4
# If you want to form a hierarchical index from multiple columns, pass a list of column numbers or names:
parsed=pd.read_csv('csv_mindex.csv',index_col=['key1','key2'])
parsed

# While you could do some munging by hand, the fields here are separated by a
# variable amount of whitespace. In these cases, you can pass a regular expression as a
# delimiter for pandas.read_csv. This can be expressed by the regular expression \s+,
# so we have then:
# result=pd.read_csv('ex3.txt',sep="\s+")
# result

pd.read_csv('ex4.csv',skiprows=[0,2,3]) #we can skip the first, third, and fourth rows of a file with skiprows

# !type ex5.csv
pd.read_csv('ex5.csv') #auto missing value handling by pandas
pd.read_csv('ex5.csv',keep_default_na=False) #we can also shut down the auto setting nan to the missing values
sentinels={'message':['foo','NA'],'something':['two']}
pd.read_csv('ex5.csv',na_values=sentinels,keep_default_na=False) #setting some specific values as nan


# path String indicating filesystem location, URL, or file-like object.
# sep or delimiter Character sequence or regular expression to use to split fields in each row.
# header Row number to use as column names; defaults to 0 (first row), but should be None if there is no
# header row.
# index_col Column numbers or names to use as the row index in the result; can be a single name/number or a
# list of them for a hierarchical index.
# names List of column names for result.
# skiprows Number of rows at beginning of file to ignore or list of row numbers (starting from 0) to skip.
# na_values Sequence of values to replace with NA. They are added to the default list unless
# keep_default_na=False is passed.
# keep_default_na Whether to use the default NA value list or not (True by default)
# parse_dates Attempt to parse data to datetime; False by default. If True, will attempt to parse all
# columns. Otherwise, can specify a list of column numbers or names to parse. If element of list is
# tuple or list, will combine multiple columns together and parse to date (e.g., if date/time split across
# two columns).
# keep_date_col If joining columns to parse date, keep the joined columns; False by default.
# converters Dictionary containing column number or name mapping to functions (e.g., {"foo": f} would
# apply the function f to all values in the "foo" column).
# dayfirst When parsing potentially ambiguous dates, treat as international format (e.g., 7/6/2012 -> June 7,
# 2012); False by default.
# date_parser Function to use to parse dates.
# nrows Number of rows to read from beginning of file (not counting the header).
# iterator Return a TextFileReader object for reading the file piecemeal. This object can also be used
# with the with statement.
# chunksize For iteration, size of file chunks.
# skip_footer Number of lines to ignore at end of file.
# verbose Print various parsing information, like the time spent in each stage of the file conversion and
# memory use information.
# encoding Text encoding (e.g., "utf-8 for UTF-8 encoded text). Defaults to "utf-8" if None.
# squeeze If the parsed data contains only one column, return a Series.
# thousands Separator for thousands (e.g., "," or "."); default is None.
# decimal Decimal separator in numbers (e.g., "." or ","); default is ".".
# engine CSV parsing and conversion engine to use; can be one of "c", "python", or "pyarrow". The
# default is "c", though the newer "pyarrow" engine can parse some files much faster. The
# "python" engine is slower but supports some features that the other engines do not.

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN