In [4]:
import numpy as np
import pandas as pd
import requests

url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url) #get http request
resp.raise_for_status()
resp
data=resp.json()
data[0]["title"]
issues=pd.DataFrame(data,columns=["numbers","title","labels","state"])
issues

,numbers,title,labels,state
0,NaN,TST(string dtype): Resolve xfails in stack_uns...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
1,NaN,ENH: Enable .mode to sort with NA values,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
2,NaN,TST(str dtype): Resolve xfail in test_value_co...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
3,NaN,TST(string dtype): Resolve xfail in test_find_...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
4,NaN,BUG: quoting=csv.QUOTE_NONNUMERIC adds extra d...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
5,NaN,Format `decimal.Decimal` as full precision str...,[],open
6,NaN,ENH: Support pipe() method in Rolling and Expa...,[],open
7,NaN,ENH: Expose NoDefault in pandas.api.extensions,[],open
8,NaN,BUG: Series constructor from dictionary drops ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
9,NaN,TST(string dtype): Resolve xfails in test_from...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
10,NaN,"ENH: add `__rshift__`, `__lshift__`, `__irshif...","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
11,NaN,ENH: Make pd.Timestamp.astimezone() default to...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
12,NaN,ENH: frozensets are shown in parentheses (like...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
13,NaN,Remove editable installs from CI,[],open
14,NaN,ENH: Better error message for trying to conver...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
15,NaN,BUG: Pandas to_sql 'Engine' object has no attr...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
16,NaN,Relax meson pins in CI,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
17,NaN,BUG: boolean series .isin([pd.NA])] inconsiste...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,NaN,BUG: scalar out of bounds input does not raise...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,NaN,ENH: Change default dtype of `str.get_dummies(...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
20,NaN,ENH: Support attrs in feather files,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
21,NaN,BUG: DataFrame.sort_values() by 2 columns and ...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
22,NaN,BUG: .to_period with MonthBegin offset does no...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
23,NaN,ENH: Add support for executing UDF's using Bod...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
24,NaN,Implement String Accumulations with nanoarrow,[],open
25,NaN,Update docs for generating unoptimized debug b...,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
26,NaN,BUG: Pandas resets counter when using filterwa...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,NaN,ENH: Enable pytables to round-trip with String...,"[{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIy...",open
28,NaN,String dtype: disallow specifying the 'str' dt...,"[{'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUy...",open
29,NaN,ENH: Remove `mode` property from `BaseBuffer`,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open